### PR TITLE
fix(functions): Fix auto-deletion of queries in TriggerManager

### PR DESCRIPTION
**Pull request by mykola-vrmchk**
### Summary
🐛🚀✨

This pull request adds query management and query by typename functionality to the echo-schema and functions packages, and improves the chess function handler and the dev-server command. It also fixes a bug in the trigger manager and updates some dependencies and path mappings in the labs-functions package.

> _The pull request had some changes to make_
> _To fix bugs and leaks for goodness sake_
> _It added `Query` and `Context` too_
> _And improved the chess function's queue_
> _With `scheduleTask` and `Trigger` in its wake_

### Walkthrough
*  Added and updated queries and triggers for echo-schema ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-718d737fa6b5a5f359faaa930b144180f7fd8dc9e3592b1ea2cc696aa2028a0cL7-R15), [link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-718d737fa6b5a5f359faaa930b144180f7fd8dc9e3592b1ea2cc696aa2028a0cR205-R233), [link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-786f42f6e60b94ab68fa74289bb879371a4b0cbca1f9af2a6279600e6c01b6efL105-R105), [link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-f9638baf083820b4fb98b23e5a82e1d408a33ff27a6cdc801d0dcd9e3ca68780L7-R7), [link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-f9638baf083820b4fb98b23e5a82e1d408a33ff27a6cdc801d0dcd9e3ca68780R28-R29), [link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-f9638baf083820b4fb98b23e5a82e1d408a33ff27a6cdc801d0dcd9e3ca68780L92-R106))
  - Implemented a new test case for query by typename in `query.test.ts` using Trigger, asyncTimeout, Query, and Contact ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-718d737fa6b5a5f359faaa930b144180f7fd8dc9e3592b1ea2cc696aa2028a0cR205-R233))
  - Passed the context to the source.changed.on callback in `query.ts` to avoid memory leaks and ensure proper disposal ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-786f42f6e60b94ab68fa74289bb879371a4b0cbca1f9af2a6279600e6c01b6efL105-R105))
  - Added a new property _queries to the TriggerManager class in `trigger-manager.ts` to store and manage Query instances ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-f9638baf083820b4fb98b23e5a82e1d408a33ff27a6cdc801d0dcd9e3ca68780R28-R29))
  - Added the query to the _queries set, updated the subscription with the initial query objects, and removed the query from the set on disposal in `trigger-manager.ts` ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-f9638baf083820b4fb98b23e5a82e1d408a33ff27a6cdc801d0dcd9e3ca68780L92-R106))
* Fixed a bug in the dev-server command for functions ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-3e3b2db2dc8e553f1bb7a0e165c4e785049885b280372fc7ddaf4fd9e99f8e49L65-R65))
  - Called triggers.stop() instead of triggers.start() on SIGINT in `dev-server.ts` to stop the trigger manager when the server is stopped ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-3e3b2db2dc8e553f1bb7a0e165c4e785049885b280372fc7ddaf4fd9e99f8e49L65-R65))
* Added the context package as a dependency and a path mapping for the labs-functions package ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-9cdc8e0cb041bc87b2b9f9463c4696bbc74b898850820cf3f0c06371c6eea85aR24), [link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-e4c4587423f7a0398291362ac5c223bd5e4f9f3e538be97e8ec74442e37bb6c5R25-R27))
  - Updated the package.json file in the labs-functions package to include the context package as a dependency ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-9cdc8e0cb041bc87b2b9f9463c4696bbc74b898850820cf3f0c06371c6eea85aR24))
  - Updated the tsconfig.json file in the labs-functions package to include the context package as a path mapping ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-e4c4587423f7a0398291362ac5c223bd5e4f9f3e538be97e8ec74442e37bb6c5R25-R27))
* Improved the chess function handler to use scheduleTask and Context ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-599b87990dc7d38396bf1c659573b8f327f007136e1268d41ee06231258b6fafR5-R6), [link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-599b87990dc7d38396bf1c659573b8f327f007136e1268d41ee06231258b6fafL12-R36))
  - Imported the scheduleTask function from the async package and the Context class from the context package in the handler.ts file in the chess function ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-599b87990dc7d38396bf1c659573b8f327f007136e1268d41ee06231258b6fafR5-R6))
  - Used the scheduleTask function instead of a setTimeout to run the chess logic asynchronously and with a context and a cancellation token in the handler.ts file in the chess function ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-599b87990dc7d38396bf1c659573b8f327f007136e1268d41ee06231258b6fafL12-R36))
  - Moved the context.status(200).succeed({}) call outside of the scheduled task in the handler.ts file in the chess function ([link](https://github.com/dxos/dxos/pull/4567/files?diff=unified&w=0#diff-599b87990dc7d38396bf1c659573b8f327f007136e1268d41ee06231258b6fafL12-R36))

### CODE REVIEW

**Comment by mykola-vrmchk** [comment]
Current dependencies on/for this PR:
* main
  * **PR #4567** <a href="https://app.graphite.dev/github/pr/dxos/dxos/4567" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dxos/dxos/4567?utm_source=stack-comment).

**Comment by Yyuot** [comment]
kanalsharing.com 13000 4567 4567

**Comment by Yyuot** [comment]
kanalsharing.com 13000 4567 4567

**Comment by Yyuot** [comment]
`kanalsharing.com 13000 4567 4567`

**Comment by Yyuot** [comment]
`kanalsharing.com 13000 4567 4567`

**Pull request merged**
