### PR TITLE
fix(react-ui-editor): Delay hiding/unhiding of markdown markup during cursor motion

### PR DESCRIPTION
**Pull request by marijnh**
To avoid disruptive popping of the content around the cursor.

Issue https://github.com/dxos/dxos/issues/5755

### CODE REVIEW

**Comment by richburdon** [comment]
I think this is useful, but it seems to introduce a problem where you can't click or cursor into the link label.

**Comment by marijnh** [comment]
Good point. I made all of the decorations atomic (so that you don't get your cursor stuck in invisible code when arrowing through markers), but only the ones that hide stuff should be. Updated the PR to fix that.

**Comment by richburdon** [comment]
Seeing another issue where the cursor loses its position (floats in whitespace) after the decoration is restored. It only seems to happen on short lines.

**Comment by marijnh** [comment]
That turned out to be an issue in CodeMirror itself. https://github.com/dxos/dxos/pull/5833 pulls in an upgrade that fixes it.

**Pull request merged**
