### PR TITLE
fix(stack): Stack creator intent might be an array

### PR DESCRIPTION
**Pull request by ZaymonFC**
- Resolves: #7655

### CODE REVIEW

**Comment by wittjosiah** [comment]
@ZaymonFC maybe rebase so this only includes your commit

**Comment by ZaymonFC** [comment]
> @ZaymonFC maybe rebase so this only includes your commit

image

**Comment by wittjosiah** [comment]
huh... I don't love that stack needs to inspect all these things...

looking at all the plugins, all of the stack creators are just a single intent anyways some are just wrapped in `[]`. I'd propose just removing the `[]` from all of those as a solution to this until we can remove stack creators altogether?

**Comment by ZaymonFC** [comment]
> huh... I don't love that stack needs to inspect all these things...
> 
> looking at all the plugins, all of the stack creators are just a single intent anyways some are just wrapped in `[]`. I'd propose just removing the `[]` from all of those as a solution to this until we can remove stack creators altogether?

That might be a better idea!

**Review by wittjosiah — APPROVED** [review]

**Pull request merged**
