### PR TITLE
refactor(react-surface): spin out plugins to packages

### PR DESCRIPTION
**Pull request by wittjosiah**
### Summary
📦🛠️📝

This pull request refactors the `composer-app` package to use the `@braneframe` plugins for graph, router, splitview, theme, and treeview functionality. The `@braneframe` plugins are more modular and specific to the composer app use case, while the `@dxos/react-surface` plugins are more generic and reusable for other applications. The pull request also updates the TypeScript, Nx, and Vite configurations to include and resolve the `@braneframe` plugins. Additionally, the pull request adds license, readme, package.json, project.json, and tsconfig.json files to the `plugin-graph` and `plugin-router` packages, which are part of the `@braneframe` plugins. The pull request also fixes some import paths in the `plugin-graph` package.

> _The composer app got a new look_
> _With `@braneframe` plugins to hook_
> _The graph and the tree_
> _The router and theme_
> _And the splitview to preview and book_

### Walkthrough
*  Replace `@dxos/react-surface` plugins with `@braneframe` plugins in `composer-app` package ([link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-47b84ac128e4ba47b697389d563eb2770189956b67cea33857501b520432a1e1L13-R18), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-9f2aee287f92edd662c13bed460a28a1590c9186b62c98ccc2e00f6877c3d7e6L11-R19), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-15b4b90f8dd36dd22e5c39505234f42035120fbeedff4c196ddcbc7b6141bbc0L8-R12), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-fb8bf0a79538b29858dc5697590cb08a4107da97d1a40c7556bb457b64acc8c8L7-R10), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-98f0022554ff912e061aa7dd2697abe11577aa9cd51cca3397012071b9c43ee7L7-R9), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-ae3c609dd132b915ae4ae4e8dc46cdae4ad74bf0a2c22dd811edddae3c999c73L9-R15), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-14fc30ee2bdca55ef0efdd64b77d7562f47879a85bb361c6fbaf19f1d8cbee8dL9-R12), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-dc0d7dcaaebbcc99c944f932f514b2033658f428c8c0bf31ed9c16ebca298de9R7-R8), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-dc0d7dcaaebbcc99c944f932f514b2033658f428c8c0bf31ed9c16ebca298de9L12-R14), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-4c3644e83729f7f016855b3a60b8f477967bcabac0650be106ffd0e7657ec163R22-R26), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-4c3644e83729f7f016855b3a60b8f477967bcabac0650be106ffd0e7657ec163L36-R41), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-aa01c591cecab0e1f8665cacbf254fc9a9418559a3649b0e930ec007c34e2d8cL78-R95), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-813f00d5c5485f0f83ea1fb6782e90691a233ccb1d82f30a61d1a956f996082eL48-R55))
* Add license, readme, package.json, project.json, tsconfig.json, and index.ts files to `plugin-graph` package ([link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-4445e58972917bbbfb030cb71dbcbf0a23d404e4839a84358b41eb42cb0b19aaL1-R7), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-8740847ec5b3f5d618d36d4b2addf95dc2b8368f3f80cc0ae6f7cf1d95592e84R1-R15), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-12132ff5f40ad790922d7afe36c3c858e243e075af7ebf71c7cba4944d991c47R1-R39), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-38a9b5eaaf5fde9d562b1c768431f23a42d28608f42b686845e718a876a6a30aR1-R47), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-e1801b9e54bef8b4efee7708bf9d8bc87c51fac66108f930623be940614f45eeR1-R33), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-a25913f9df0d775f9b1625b437ce8d1b056d721defad8e831dc9c613fd54a115R1-R5))
* Import `@dxos/react-surface` package instead of internal path in `GraphPlugin.tsx` file of `plugin-graph` package ([link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-93bf3cf06a0c1cea035e8647088f2523ff84452883582dabc6e93e7cbcc8cb97L5-R10))
* Add license and readme files to `plugin-router` package ([link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-4058c97adf2d87ee2b979cc0910fbe992b08d69cb3a03456c4042b3cf25cf6efL1-R7), [link](https://github.com/dxos/dxos/pull/3540/files?diff=unified&w=0#diff-ecb4c2712306f9e6be00d967a7aa85018c22a76f611f190d0c778ffea8a81606R1-R15))

### CODE REVIEW

**Comment by wittjosiah** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3540** <a href="https://app.graphite.dev/github/pr/dxos/dxos/3540" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dxos/dxos/3540?utm_source=stack-comment).

**Review by thure — APPROVED** [review]
Fantastic! Looking forward to this.

**Comment by wittjosiah** [comment]
@wittjosiah started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dxos/dxos/3540).

**Comment by wittjosiah** [comment]
@wittjosiah merged this pull request with [Graphite](https://app.graphite.dev/github/pr/dxos/dxos/3540).

**Pull request merged**
