### PR TITLE
fix(react-ui-editor): Make it easier to move the cursor into tables

### PR DESCRIPTION
**Pull request by marijnh**
With keyboard, by not making this a block widget (which is skipped in vertical arrow motion), and with mouse, by letting the editor handle mouse clicks on the table.

### CODE REVIEW

**Comment by marijnh** [comment]
The CI failure is `fatal: Could not read from remote repository.`, which doesn't sound like an issue introduced by the patch. I don't seem to have the power to restart the test run, I think.

**Comment by mykola-vrmchk** [comment]
> The CI failure is `fatal: Could not read from remote repository.`, which doesn't sound like an issue introduced by the patch. I don't have the power to restart the test run, I think.

@marijnh , I restarted it for you

**Comment by marijnh** [comment]
Thanks. Not sure what "Validate PR title" is waiting for now, but the CI seems to have run.

@richburdon This is ready for review too.

**Review by thure — APPROVED** [review]
lgtm

**Pull request merged**
