### PR TITLE
fix(halo-app): sentry in shared worker

### PR DESCRIPTION
**Pull request by wittjosiah**
Note: Brave shields seem to block sentry requests in workers even when they are disabled https://github.com/brave/brave-browser/issues/25958

### CODE REVIEW

**Comment by wittjosiah** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2796** <a href="https://app.graphite.dev/github/pr/dxos/dxos/2796" target="_blank">Graphite</a> 
    * **PR #2799** <a href="https://app.graphite.dev/github/pr/dxos/dxos/2799" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dxos/dxos/2799?utm_source=stack-comment).

**Review by dmaretskyi — APPROVED** [review]

**Comment by wittjosiah** [comment]
@wittjosiah queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/dxos/dxos/2799).

**Comment by wittjosiah** [comment]
[Graphite](https://app.graphite.dev/github/pr/dxos/dxos/2799) rebased this pull request as part of a merge.

**Comment by wittjosiah** [comment]
[Graphite](https://app.graphite.dev/github/pr/dxos/dxos/2799) couldn't merge this PR because it was not satisfying all requirements.

**Pull request merged**
